use_frameworks!

platform :ios, '10.0'

target 'Core_Example' do
  pod 'Core', :path => '../'
#  pod 'Network', git: 'https://github.com/syquandev/Network'
  target 'Core_Tests' do
    inherit! :search_paths

    
  end
end
